# Downloading Google Trends Data
Google trends data can be quite usefull to understand behavioral differences in response to a public health risk, particulary when it comes to gauging the perception of such risk.

The GGtrends module from Epigraphhub returns the results as convenient pandas dataframes.

In [1]:
from epigraphhub.data.ggtrends import (
    historical_interest,
    interest_by_region,
    interest_over_time,
)

Let's try a first search by region.

In [2]:
keywords = ["covid", "vaccine"]
interest_by_region(keywords)

               geoCode  covid  vaccine
geoName
Afghanistan         AF     59       41
Albania             AL     89       11
Algeria             DZ     97        3
American Samoa      AS     85       15
Andorra             AD     99        1
...                ...    ...      ...
Western Sahara      EH     98        2
Yemen               YE     59       41
Zambia              ZM     69       31
Zimbabwe            ZW     88       12
Åland Islands       AX     95        5

[250 rows x 3 columns]

In [3]:
interest_over_time(keywords)

            covid  vaccine  isPartial
date
2021-09-26     45       11      False
2021-10-03     42       11      False
2021-10-10     41       11      False
2021-10-17     41       11      False
2021-10-24     39        9      False
2021-10-31     39        9      False
2021-11-07     42       10      False
2021-11-14     43        9      False
2021-11-21     49        8      False
2021-11-28     53       10      False
2021-12-05     50        9      False
2021-12-12     70       14      False
2021-12-19     80        9      False
2021-12-26     96        8      False
2022-01-02    100       10      False
2022-01-09     91        9      False
2022-01-16     88       24      False
2022-01-23     58        6      False
2022-01-30     48        5      False
2022-02-06     40        5      False
2022-02-13     34        4      False
2022-02-20     32        4      False
2022-02-27     28        4      False
2022-03-06     25        3      False
2022-03-13     26        3      False
2022-03-20     26        3      False
2022-03-27     25        3      False
2022-04-03     23        3      False
2022-04-10     21        3      False
2022-04-17     20        3      False
2022-04-24     20        3      False
2022-05-01     19        2      False
2022-05-08     18        2      False
2022-05-15     19        2      False
2022-05-22     17        3      False
2022-05-29     17        2      False
2022-06-05     18        2      False
2022-06-12     17        2      False
2022-06-19     20        3      False
2022-06-26     21        2      False
2022-07-03     23        2      False
2022-07-10     24        2      False
2022-07-17     22        3      False
2022-07-24     19        3      False
2022-07-31     16        3      False
2022-08-07     14        3      False
2022-08-14     13        2      False
2022-08-21     12        2      False
2022-08-28     12        2      False
2022-09-04     11        2      False
2022-09-11     11        2      False

In [4]:
historical_interest(keywords)

/Users/eduardoaraujo/mambaforge/envs/epigraphhub_py/lib/python3.9/site-packages/pytrends/request.py:589: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(week_df)
/Users/eduardoaraujo/mambaforge/envs/epigraphhub_py/lib/python3.9/site-packages/pytrends/request.py:589: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(week_df)
/Users/eduardoaraujo/mambaforge/envs/epigraphhub_py/lib/python3.9/site-packages/pytrends/request.py:589: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(week_df)
/Users/eduardoaraujo/mambaforge/envs/epigraphhub_py/lib/python3.9/site-packages/pytrends/request.py:589: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(week_df)
/Users/eduardoaraujo/mambaforge/envs/epigraphhub_py/lib/python3.9/site-packages/pytrends/request.py:611: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(week_df)

                     covid  vaccine  isPartial
date
2021-09-01 00:00:00     62       14      False
2021-09-01 01:00:00     67       15      False
2021-09-01 02:00:00     61       15      False
2021-09-01 03:00:00     57       17      False
2021-09-01 04:00:00     64       32      False
...                    ...      ...        ...
2021-09-29 20:00:00     76       16      False
2021-09-29 21:00:00     83       20      False
2021-09-29 22:00:00     91       23      False
2021-09-29 23:00:00     96       21      False
2021-09-30 00:00:00    100       22      False

[701 rows x 3 columns]